<?php

namespace AppBundle\Repository;

/**
 * LinkSourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkSourceRepository extends \Doctrine\ORM\EntityRepository
{
}
