<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LinkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinkRepository extends EntityRepository
{

    public function getHierarchicalFromRoot($id)
    {
        $stt = $this->getEntityManager()->getConnection()->prepare(
            'select l.id, l.parent_id, l.url, l.status_code, l.status_message from link l
            where l.root_id = :id
            ORDER BY COALESCE(parent_id, id), parent_id IS NOT NULL, id'
        );
        $stt->bindParam(':id', $id);
        $stt->execute();

        $result = $stt->fetchAll();
        return $result;
    }
}
