fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: '@AppBundle/Controller/'
    type: annotation

easy_admin_bundle:
    resource: "@AppBundle/Admin/DefaultController.php"
#    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin