# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
          - { name: twig.extension }

    app.link_processor:
        class: AppBundle\Services\LinkProcessor
        arguments: ['@app.guzzle.client', '@doctrine.orm.default_entity_manager']

    app.guzzle.client:
#        class: GuzzleHttp\Client
        class: AppBundle\Services\HttpClient
        arguments:
            - {allow_redirects: {track_redirects: true, max: 10, strict: false, referer: false}, http_errors: false}

